repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      exclude: ^tests/
      language_version: python3.7

-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v2.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: flake8
    -   id: requirements-txt-fixer
    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'master'
    hooks:
    -   id: autopep8
